"""add v2 data model rag prompts gamification tracing

Revision ID: 57b27dd8249a
Revises: 34dfb9b1cc96
Create Date: 2026-07-04 21:02:24.552687
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '57b27dd8249a'
down_revision: Union[str, None] = '34dfb9b1cc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('criteria_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_key'), 'prompt_templates', ['key'], unique=False)
    # Partial unique index: at most ONE active prompt per key, while still
    # allowing many archived (is_active = false) versions to coexist.
    op.create_index(
        "ux_prompt_templates_active_key",
        "prompt_templates",
        ["key"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prompt_template_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_template_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_template_history_prompt_template_id'), 'prompt_template_history', ['prompt_template_id'], unique=False)
    op.create_table('student_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'badge_id', name='uq_student_badge')
    )
    op.create_table('teacher_courses',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'co_teacher')", name='ck_teacher_course_role'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_table('content_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_chunks_module_id'), 'content_chunks', ['module_id'], unique=False)
    op.create_index(op.f('ix_content_chunks_subject_id'), 'content_chunks', ['subject_id'], unique=False)
    # HNSW index for fast approximate nearest-neighbour search over embeddings.
    # Cosine distance (vector_cosine_ops) is the standard for semantic search on
    # normalized embeddings. m / ef_construction are sensible defaults, tunable later.
    # (Not emitted by autogenerate — pgvector indexes must be declared by hand.)
    op.create_index(
        "ix_content_chunks_embedding_hnsw",
        "content_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.add_column('students', sa.Column('xp_points', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('students', sa.Column('current_streak_days', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('students', sa.Column('badges_earned', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'badges_earned')
    op.drop_column('students', 'current_streak_days')
    op.drop_column('students', 'xp_points')
    op.drop_index("ix_content_chunks_embedding_hnsw", table_name="content_chunks")
    op.drop_index(op.f('ix_content_chunks_subject_id'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_module_id'), table_name='content_chunks')
    op.drop_table('content_chunks')
    op.drop_table('teacher_courses')
    op.drop_table('student_badges')
    op.drop_index(op.f('ix_prompt_template_history_prompt_template_id'), table_name='prompt_template_history')
    op.drop_table('prompt_template_history')
    op.drop_table('teachers')
    op.drop_index("ux_prompt_templates_active_key", table_name="prompt_templates")
    op.drop_index(op.f('ix_prompt_templates_key'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_table('badges')
    # ### end Alembic commands ###
