"""add external_id to subjects and modules for openedx sync

Revision ID: 6dbb1d73935c
Revises: 57b27dd8249a
Create Date: 2026-07-16 08:41:54.856220
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbb1d73935c'
down_revision: Union[str, None] = '57b27dd8249a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_modules_external_id'), 'modules', ['external_id'], unique=True)
    op.add_column('subjects', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subjects_external_id'), 'subjects', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_external_id'), table_name='subjects')
    op.drop_column('subjects', 'external_id')
    op.drop_index(op.f('ix_modules_external_id'), table_name='modules')
    op.drop_column('modules', 'external_id')
    # ### end Alembic commands ###
